// <auto-generated />
namespace API.Queries.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class set_qtyInvID_on_invRecord_to_nullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(set_qtyInvID_on_invRecord_to_nullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201907170313564_set_qtyInvID_on_invRecord_to_nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
