// <auto-generated />
namespace API.Queries.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_inv_stat_and_inv_stat_id_on_qty_inv : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_inv_stat_and_inv_stat_id_on_qty_inv));
        
        string IMigrationMetadata.Id
        {
            get { return "201907290053493_add_inv_stat_and_inv_stat_id_on_qty_inv"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
