// <auto-generated />
namespace API.Queries.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateinventoryrecordguid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateinventoryrecordguid));
        
        string IMigrationMetadata.Id
        {
            get { return "201909302159085_update-inventoryrecord-guid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
