// <auto-generated />
namespace API.Queries.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class transfer_date_acquired_to_inventory_records : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(transfer_date_acquired_to_inventory_records));
        
        string IMigrationMetadata.Id
        {
            get { return "201907020759034_transfer_date_acquired_to_inventory_records"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
