// <auto-generated />
namespace API.Queries.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class change_userGuid_property : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_userGuid_property));
        
        string IMigrationMetadata.Id
        {
            get { return "201910010404188_change_userGuid_property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
