// <auto-generated />
namespace API.Queries.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_identity_ID_to_guid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_identity_ID_to_guid));
        
        string IMigrationMetadata.Id
        {
            get { return "201909212133413_update_identity_ID_to_guid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
