// <auto-generated />
namespace API.Queries.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class set_date_acquired_null : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(set_date_acquired_null));
        
        string IMigrationMetadata.Id
        {
            get { return "201907120107355_set_date_acquired_null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
