// <auto-generated />
namespace API.Queries.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_code_column_to_inv_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_code_column_to_inv_type));
        
        string IMigrationMetadata.Id
        {
            get { return "201907090233089_add_code_column_to_inv_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
