// <auto-generated />
namespace API.Queries.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitialClassScheduleEntities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialClassScheduleEntities));
        
        string IMigrationMetadata.Id
        {
            get { return "202007101439464_InitialClassScheduleEntities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
